#version: "3"
#
#services:
#  localstack:
#    image: localstack/localstack:0.11.2
#    ports:
#      - "4567-4584:4567-4584"
#      - "8085:8080"
#    environment:
#      - SERVICES=sqs,s3
#    volumes:
#      - './.localstack:/tmp/localstack'
#      - '/var/run/docker.sock:/var/run/docker.sock'
#    networks:
#      aws_network:
#        ipv4_address: 172.22.0.6

version: '3.7'

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:0.11.2
    environment:
      - DEBUG=1
      - USE_SSL=0
      - AWS_CBOR_DISABLE=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME=localstack
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - '4566-4583:4566-4583'
    volumes:
      - ./.localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./init-s3.sh:/docker-entrypoint-initaws.d/init-s3.sh
